### ISSUE TITLE
Tkinter cannot load the icon so the program crashes

### ISSUE THREAD

**Issue by Poikilos** [kavehtehrani/world_clock#3]
For some reason, some ICO files are Windows-only. I never ran into this problem before. The error is:
```
Traceback (most recent call last):
  File "world_clock.py", line 119, in <module>
    root.iconbitmap(r'clock_mini_icon.ico')
  File "/usr/lib/python3.7/tkinter/__init__.py", line 1871, in wm_iconbitmap
    return self.tk.call('wm', 'iconbitmap', self._w, bitmap)
_tkinter.TclError: bitmap "clock_mini_icon.ico" not defined
```
None of the following helped
- See <https://stackoverflow.com/questions/11176638/tkinter-tclerror-error-reading-bitmap-file>
  Apparently no ICO files work in Linux and that is a tkinter limitation not a Linux limitation.
  None of the following commented or uncommented code worked:
```Python
    if platform.system() == "Windows":
        root.iconbitmap(r'clock_mini_icon.ico')
    else:
        # See <https://stackoverflow.com/questions/16081201/
        #   setting-application-icon-in-my-python-tk-base-application-
        #   on-ubuntu>.
        # iconPath = os.path.realpath('clock_mini_icon.ico')
        iconPath = os.path.realpath('clock_mini_icon.png')
        # iconPath = os.path.realpath('clock_mini_icon.gif')
        # iconPath = os.path.realpath('clock_mini_icon.xbm')
        # img = tk.PhotoImage(iconPath)
        # img = tk.Image("photo", file=iconPath)
        # ^ no error but no display using root.tk.call iconphoto
        img = tk.PhotoImage(file=iconPath)
        # root.iconphoto(True, img)
        # root.iconbitmap("@clock_mini_icon.xbm")  # necessary for xbm
        # root.tk.call('wm', 'iconphoto', root._w, img)
        # print("root.tk: {}".format(type(root.tk)))  # _tkinter.tkapp
        # print("root._w: {}".format(type(root._w)))  # str
        # label = tk.Label(image=img)
        # root.iconwindow(label)
        # ^ "_tkinter.TclError: can't use .!label as icon window: not at
        #   top level"
        # root.iconbitmap(iconPath)
        # ^ "_tkinter.TclError: bitmap ... not defined"
        root.tk.call('wm', 'iconphoto', root._w, img)

```

The code also cites:
- https://stackoverflow.com/questions/16081201/setting-application-icon-in-my-python-tk-base-application-on-ubuntu
- https://stackoverflow.com/questions/35024118/how-to-load-an-image-into-a-python-3-4-tkinter-window

Current state of code:
- I am not sure why this is working for someone on Ubuntu 18.04 but it is not working on Debian 10 for me.
  - https://python-forum.io/thread-28833.html
- In any case, the code prevents a crash and the program works, but the icon doesn't change.

**Comment by kavehtehrani** [comment]
Thanks. Will take a look. Runs fine on Ubuntu 20.04 and Windows 10, will investigate.
